inputs_outputs_basepath: "C:/Users/dvir/Downloads/codenet/generated_test_cases"
reference_file_path: "data/tasks/pie/codenet-python-test-1k.jsonl"
num_problems_to_evaluate: -1
num_trials: 1
ignore_first_k: 0
max_time_per_run: 10
temp_dir: null
model_generated_potentially_faster_code_col: "attempt_0_code"
slow_code_col: "input"
reference_code_col: "target"
is_prompt_based: false
language: python
return_if_acc_below: 1.0
# Removed because the script doesnt know this value.
# num_processes: 60
cpu_number: 15
output_report_file_path: "TO_BE_UPDATED"
model_generated_outputs_path: "TO_BE_UPDATED"